Imports Telerik.WinControls.UI

<Global.Microsoft.VisualBasic.CompilerServices.DesignerGenerated()> _
Partial Class RadForm1
    Inherits RadForm

    'Form overrides dispose to clean up the component list.
    <System.Diagnostics.DebuggerNonUserCode()> _
    Protected Overrides Sub Dispose(ByVal disposing As Boolean)
        Try
            If disposing AndAlso components IsNot Nothing Then
                components.Dispose()
            End If
        Finally
            MyBase.Dispose(disposing)
        End Try
    End Sub

    'Required by the Windows Form Designer
    Private components As System.ComponentModel.IContainer

    'NOTE: The following procedure is required by the Windows Form Designer
    'It can be modified using the Windows Form Designer.  
    'Do not modify it using the code editor.
    <System.Diagnostics.DebuggerStepThrough()> _
    Private Sub InitializeComponent()
        Me.components = New System.ComponentModel.Container
        Dim GridViewDecimalColumn1 As Telerik.WinControls.UI.GridViewDecimalColumn = New Telerik.WinControls.UI.GridViewDecimalColumn
        Dim GridViewTextBoxColumn1 As Telerik.WinControls.UI.GridViewTextBoxColumn = New Telerik.WinControls.UI.GridViewTextBoxColumn
        Dim GridViewTextBoxColumn2 As Telerik.WinControls.UI.GridViewTextBoxColumn = New Telerik.WinControls.UI.GridViewTextBoxColumn
        Dim GridViewImageColumn1 As Telerik.WinControls.UI.GridViewImageColumn = New Telerik.WinControls.UI.GridViewImageColumn
        Me.productsBindingSource = New System.Windows.Forms.BindingSource(Me.components)
        Me.furnitureDataSet = New GettingStarted.FurnitureDataSet
        Me.productsTableAdapter = New GettingStarted.FurnitureDataSetTableAdapters.ProductsTableAdapter
        Me.radMultiColumnComboBox1 = New Telerik.WinControls.UI.RadMultiColumnComboBox
        CType(Me.productsBindingSource, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.furnitureDataSet, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.radMultiColumnComboBox1, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.radMultiColumnComboBox1.EditorControl, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.radMultiColumnComboBox1.EditorControl.MasterTemplate, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me, System.ComponentModel.ISupportInitialize).BeginInit()
        Me.SuspendLayout()
        '
        'productsBindingSource
        '
        Me.productsBindingSource.DataMember = "Products"
        Me.productsBindingSource.DataSource = Me.furnitureDataSet
        '
        'furnitureDataSet
        '
        Me.furnitureDataSet.DataSetName = "FurnitureDataSet"
        Me.furnitureDataSet.SchemaSerializationMode = System.Data.SchemaSerializationMode.IncludeSchema
        '
        'productsTableAdapter
        '
        Me.productsTableAdapter.ClearBeforeFill = True
        '
        'radMultiColumnComboBox1
        '
        Me.radMultiColumnComboBox1.DataSource = Me.productsBindingSource
        Me.radMultiColumnComboBox1.DisplayMember = "ProductName"
        Me.radMultiColumnComboBox1.DropDownSizingMode = CType((Telerik.WinControls.UI.SizingMode.RightBottom Or Telerik.WinControls.UI.SizingMode.UpDown), Telerik.WinControls.UI.SizingMode)
        '
        'radMultiColumnComboBox1.NestedRadGridView
        '
        Me.radMultiColumnComboBox1.EditorControl.BackColor = System.Drawing.SystemColors.ControlLightLight
        Me.radMultiColumnComboBox1.EditorControl.Font = New System.Drawing.Font("Microsoft Sans Serif", 8.25!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
        Me.radMultiColumnComboBox1.EditorControl.ForeColor = System.Drawing.SystemColors.ControlText
        Me.radMultiColumnComboBox1.EditorControl.Location = New System.Drawing.Point(4, 1)
        '
        '
        '
        Me.radMultiColumnComboBox1.EditorControl.MasterTemplate.AllowAddNewRow = False
        Me.radMultiColumnComboBox1.EditorControl.MasterTemplate.AllowCellContextMenu = False
        Me.radMultiColumnComboBox1.EditorControl.MasterTemplate.AllowColumnChooser = False
        GridViewDecimalColumn1.DataType = GetType(Integer)
        GridViewDecimalColumn1.FieldName = "ID"
        GridViewDecimalColumn1.HeaderText = "ID"
        GridViewDecimalColumn1.IsAutoGenerated = True
        GridViewDecimalColumn1.Name = "ID"
        GridViewDecimalColumn1.TextAlignment = System.Drawing.ContentAlignment.MiddleRight
        GridViewTextBoxColumn1.FieldName = "ProductName"
        GridViewTextBoxColumn1.HeaderText = "ProductName"
        GridViewTextBoxColumn1.IsAutoGenerated = True
        GridViewTextBoxColumn1.Name = "ProductName"
        GridViewTextBoxColumn2.FieldName = "Manufacturer"
        GridViewTextBoxColumn2.HeaderText = "Manufacturer"
        GridViewTextBoxColumn2.IsAutoGenerated = True
        GridViewTextBoxColumn2.Name = "Manufacturer"
        GridViewImageColumn1.DataType = GetType(Byte())
        GridViewImageColumn1.FieldName = "Photo"
        GridViewImageColumn1.HeaderText = "Photo"
        GridViewImageColumn1.IsAutoGenerated = True
        GridViewImageColumn1.Name = "Photo"
        Me.radMultiColumnComboBox1.EditorControl.MasterTemplate.Columns.AddRange(New Telerik.WinControls.UI.GridViewDataColumn() {GridViewDecimalColumn1, GridViewTextBoxColumn1, GridViewTextBoxColumn2, GridViewImageColumn1})
        Me.radMultiColumnComboBox1.EditorControl.MasterTemplate.DataSource = Me.productsBindingSource
        Me.radMultiColumnComboBox1.EditorControl.MasterTemplate.EnableGrouping = False
        Me.radMultiColumnComboBox1.EditorControl.MasterTemplate.ShowFilteringRow = False
        Me.radMultiColumnComboBox1.EditorControl.Name = "NestedRadGridView"
        Me.radMultiColumnComboBox1.EditorControl.ReadOnly = True
        Me.radMultiColumnComboBox1.EditorControl.ShowGroupPanel = False
        Me.radMultiColumnComboBox1.EditorControl.Size = New System.Drawing.Size(292, 104)
        Me.radMultiColumnComboBox1.EditorControl.TabIndex = 0
        Me.radMultiColumnComboBox1.EditorControl.Visible = False
        Me.radMultiColumnComboBox1.Font = New System.Drawing.Font("Arial", 8.25!)
        Me.radMultiColumnComboBox1.ForeColor = System.Drawing.Color.FromArgb(CType(CType(51, Byte), Integer), CType(CType(51, Byte), Integer), CType(CType(51, Byte), Integer))
        Me.radMultiColumnComboBox1.Location = New System.Drawing.Point(23, 26)
        Me.radMultiColumnComboBox1.Name = "radMultiColumnComboBox1"
        '
        '
        '
        Me.radMultiColumnComboBox1.RootElement.AutoSizeMode = Telerik.WinControls.RadAutoSizeMode.WrapAroundChildren
        Me.radMultiColumnComboBox1.RootElement.ForeColor = System.Drawing.Color.FromArgb(CType(CType(51, Byte), Integer), CType(CType(51, Byte), Integer), CType(CType(51, Byte), Integer))
        Me.radMultiColumnComboBox1.Size = New System.Drawing.Size(154, 18)
        Me.radMultiColumnComboBox1.TabIndex = 0
        Me.radMultiColumnComboBox1.TabStop = False
        Me.radMultiColumnComboBox1.ThemeName = "ControlDefault"
        Me.radMultiColumnComboBox1.ValueMember = "ProductName"
        '
        'RadForm1
        '
        Me.AutoScaleDimensions = New System.Drawing.SizeF(6.0!, 13.0!)
        Me.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font
        Me.ClientSize = New System.Drawing.Size(392, 279)
        Me.Controls.Add(Me.radMultiColumnComboBox1)
        Me.Font = New System.Drawing.Font("Arial", 8.25!)
        Me.Name = "RadForm1"
        '
        '
        '
        Me.RootElement.ApplyShapeToControl = True
        Me.Text = "MultiColumnComboBox"
        Me.ThemeName = "ControlDefault"
        CType(Me.productsBindingSource, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.furnitureDataSet, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.radMultiColumnComboBox1.EditorControl.MasterTemplate, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.radMultiColumnComboBox1.EditorControl, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.radMultiColumnComboBox1, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me, System.ComponentModel.ISupportInitialize).EndInit()
        Me.ResumeLayout(False)
        Me.PerformLayout()

    End Sub

    Private furnitureDataSet As FurnitureDataSet
    Private productsBindingSource As System.Windows.Forms.BindingSource
    Private productsTableAdapter As GettingStarted.FurnitureDataSetTableAdapters.ProductsTableAdapter
    Private radMultiColumnComboBox1 As Telerik.WinControls.UI.RadMultiColumnComboBox
End Class
