'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4952
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

<Assembly: Global.System.Data.Objects.DataClasses.EdmSchemaAttribute("6b45e5bd-7314-4374-a116-7b000ed830ae"),  _
 Assembly: Global.System.Data.Objects.DataClasses.EdmRelationshipAttribute("NorthwindModel", "FK_Products_Suppliers", "Suppliers", Global.System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, GetType(Suppliers), "Products", Global.System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Products))> 

'Original file name:
'Generation date: 4/8/2011 5:03:42 PM
'''<summary>
'''There are no comments for NorthwindEntities in the schema.
'''</summary>
Partial Public Class NorthwindEntities
    Inherits Global.System.Data.Objects.ObjectContext
    '''<summary>
    '''Initializes a new NorthwindEntities object using the connection string found in the 'NorthwindEntities' section of the application configuration file.
    '''</summary>
    Public Sub New()
        MyBase.New("name=NorthwindEntities", "NorthwindEntities")
        Me.OnContextCreated
    End Sub
    '''<summary>
    '''Initialize a new NorthwindEntities object.
    '''</summary>
    Public Sub New(ByVal connectionString As String)
        MyBase.New(connectionString, "NorthwindEntities")
        Me.OnContextCreated
    End Sub
    '''<summary>
    '''Initialize a new NorthwindEntities object.
    '''</summary>
    Public Sub New(ByVal connection As Global.System.Data.EntityClient.EntityConnection)
        MyBase.New(connection, "NorthwindEntities")
        Me.OnContextCreated
    End Sub
    Partial Private Sub OnContextCreated()
        End Sub
    '''<summary>
    '''There are no comments for Products in the schema.
    '''</summary>
    Public ReadOnly Property Products() As Global.System.Data.Objects.ObjectQuery(Of Products)
        Get
            If (Me._Products Is Nothing) Then
                Me._Products = MyBase.CreateQuery(Of Products)("[Products]")
            End If
            Return Me._Products
        End Get
    End Property
    Private _Products As Global.System.Data.Objects.ObjectQuery(Of Products)
    '''<summary>
    '''There are no comments for Suppliers in the schema.
    '''</summary>
    Public ReadOnly Property Suppliers() As Global.System.Data.Objects.ObjectQuery(Of Suppliers)
        Get
            If (Me._Suppliers Is Nothing) Then
                Me._Suppliers = MyBase.CreateQuery(Of Suppliers)("[Suppliers]")
            End If
            Return Me._Suppliers
        End Get
    End Property
    Private _Suppliers As Global.System.Data.Objects.ObjectQuery(Of Suppliers)
    '''<summary>
    '''There are no comments for Products in the schema.
    '''</summary>
    Public Sub AddToProducts(ByVal products As Products)
        MyBase.AddObject("Products", products)
    End Sub
    '''<summary>
    '''There are no comments for Suppliers in the schema.
    '''</summary>
    Public Sub AddToSuppliers(ByVal suppliers As Suppliers)
        MyBase.AddObject("Suppliers", suppliers)
    End Sub
End Class
'''<summary>
'''There are no comments for NorthwindModel.Products in the schema.
'''</summary>
'''<KeyProperties>
'''ProductID
'''</KeyProperties>
<Global.System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName:="NorthwindModel", Name:="Products"),  _
 Global.System.Runtime.Serialization.DataContractAttribute(IsReference:=true),  _
 Global.System.Serializable()>  _
Partial Public Class Products
    Inherits Global.System.Data.Objects.DataClasses.EntityObject
    '''<summary>
    '''Create a new Products object.
    '''</summary>
    '''<param name="productID">Initial value of ProductID.</param>
    '''<param name="productName">Initial value of ProductName.</param>
    '''<param name="discontinued">Initial value of Discontinued.</param>
    Public Shared Function CreateProducts(ByVal productID As Integer, ByVal productName As String, ByVal discontinued As Boolean) As Products
        Dim products As Products = New Products
        products.ProductID = productID
        products.ProductName = productName
        products.Discontinued = discontinued
        Return products
    End Function
    '''<summary>
    '''There are no comments for Property ProductID in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property ProductID() As Integer
        Get
            Return Me._ProductID
        End Get
        Set
            Me.OnProductIDChanging(value)
            Me.ReportPropertyChanging("ProductID")
            Me._ProductID = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("ProductID")
            Me.OnProductIDChanged
        End Set
    End Property
    Private _ProductID As Integer
    Partial Private Sub OnProductIDChanging(ByVal value As Integer)
        End Sub
    Partial Private Sub OnProductIDChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property ProductName in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property ProductName() As String
        Get
            Return Me._ProductName
        End Get
        Set
            Me.OnProductNameChanging(value)
            Me.ReportPropertyChanging("ProductName")
            Me._ProductName = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false)
            Me.ReportPropertyChanged("ProductName")
            Me.OnProductNameChanged
        End Set
    End Property
    Private _ProductName As String
    Partial Private Sub OnProductNameChanging(ByVal value As String)
        End Sub
    Partial Private Sub OnProductNameChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property CategoryID in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property CategoryID() As Global.System.Nullable(Of Integer)
        Get
            Return Me._CategoryID
        End Get
        Set
            Me.OnCategoryIDChanging(value)
            Me.ReportPropertyChanging("CategoryID")
            Me._CategoryID = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("CategoryID")
            Me.OnCategoryIDChanged
        End Set
    End Property
    Private _CategoryID As Global.System.Nullable(Of Integer)
    Partial Private Sub OnCategoryIDChanging(ByVal value As Global.System.Nullable(Of Integer))
        End Sub
    Partial Private Sub OnCategoryIDChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property QuantityPerUnit in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property QuantityPerUnit() As String
        Get
            Return Me._QuantityPerUnit
        End Get
        Set
            Me.OnQuantityPerUnitChanging(value)
            Me.ReportPropertyChanging("QuantityPerUnit")
            Me._QuantityPerUnit = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
            Me.ReportPropertyChanged("QuantityPerUnit")
            Me.OnQuantityPerUnitChanged
        End Set
    End Property
    Private _QuantityPerUnit As String
    Partial Private Sub OnQuantityPerUnitChanging(ByVal value As String)
        End Sub
    Partial Private Sub OnQuantityPerUnitChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property UnitPrice in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property UnitPrice() As Global.System.Nullable(Of Decimal)
        Get
            Return Me._UnitPrice
        End Get
        Set
            Me.OnUnitPriceChanging(value)
            Me.ReportPropertyChanging("UnitPrice")
            Me._UnitPrice = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("UnitPrice")
            Me.OnUnitPriceChanged
        End Set
    End Property
    Private _UnitPrice As Global.System.Nullable(Of Decimal)
    Partial Private Sub OnUnitPriceChanging(ByVal value As Global.System.Nullable(Of Decimal))
        End Sub
    Partial Private Sub OnUnitPriceChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property UnitsInStock in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property UnitsInStock() As Global.System.Nullable(Of Short)
        Get
            Return Me._UnitsInStock
        End Get
        Set
            Me.OnUnitsInStockChanging(value)
            Me.ReportPropertyChanging("UnitsInStock")
            Me._UnitsInStock = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("UnitsInStock")
            Me.OnUnitsInStockChanged
        End Set
    End Property
    Private _UnitsInStock As Global.System.Nullable(Of Short)
    Partial Private Sub OnUnitsInStockChanging(ByVal value As Global.System.Nullable(Of Short))
        End Sub
    Partial Private Sub OnUnitsInStockChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property UnitsOnOrder in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property UnitsOnOrder() As Global.System.Nullable(Of Short)
        Get
            Return Me._UnitsOnOrder
        End Get
        Set
            Me.OnUnitsOnOrderChanging(value)
            Me.ReportPropertyChanging("UnitsOnOrder")
            Me._UnitsOnOrder = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("UnitsOnOrder")
            Me.OnUnitsOnOrderChanged
        End Set
    End Property
    Private _UnitsOnOrder As Global.System.Nullable(Of Short)
    Partial Private Sub OnUnitsOnOrderChanging(ByVal value As Global.System.Nullable(Of Short))
        End Sub
    Partial Private Sub OnUnitsOnOrderChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property ReorderLevel in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property ReorderLevel() As Global.System.Nullable(Of Short)
        Get
            Return Me._ReorderLevel
        End Get
        Set
            Me.OnReorderLevelChanging(value)
            Me.ReportPropertyChanging("ReorderLevel")
            Me._ReorderLevel = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("ReorderLevel")
            Me.OnReorderLevelChanged
        End Set
    End Property
    Private _ReorderLevel As Global.System.Nullable(Of Short)
    Partial Private Sub OnReorderLevelChanging(ByVal value As Global.System.Nullable(Of Short))
        End Sub
    Partial Private Sub OnReorderLevelChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property Discontinued in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Discontinued() As Boolean
        Get
            Return Me._Discontinued
        End Get
        Set
            Me.OnDiscontinuedChanging(value)
            Me.ReportPropertyChanging("Discontinued")
            Me._Discontinued = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("Discontinued")
            Me.OnDiscontinuedChanged
        End Set
    End Property
    Private _Discontinued As Boolean
    Partial Private Sub OnDiscontinuedChanging(ByVal value As Boolean)
        End Sub
    Partial Private Sub OnDiscontinuedChanged()
        End Sub
    '''<summary>
    '''There are no comments for Suppliers in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("NorthwindModel", "FK_Products_Suppliers", "Suppliers"),  _
     Global.System.Xml.Serialization.XmlIgnoreAttribute(),  _
     Global.System.Xml.Serialization.SoapIgnoreAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Suppliers() As Suppliers
        Get
            Return CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Suppliers)("NorthwindModel.FK_Products_Suppliers", "Suppliers").Value
        End Get
        Set
            CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Suppliers)("NorthwindModel.FK_Products_Suppliers", "Suppliers").Value = value
        End Set
    End Property
    '''<summary>
    '''There are no comments for Suppliers in the schema.
    '''</summary>
    <Global.System.ComponentModel.BrowsableAttribute(false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property SuppliersReference() As Global.System.Data.Objects.DataClasses.EntityReference(Of Suppliers)
        Get
            Return CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Suppliers)("NorthwindModel.FK_Products_Suppliers", "Suppliers")
        End Get
        Set
            If (Not (value) Is Nothing) Then
                CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Suppliers)("NorthwindModel.FK_Products_Suppliers", "Suppliers", value)
            End If
        End Set
    End Property
End Class
'''<summary>
'''There are no comments for NorthwindModel.Suppliers in the schema.
'''</summary>
'''<KeyProperties>
'''SupplierID
'''</KeyProperties>
<Global.System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName:="NorthwindModel", Name:="Suppliers"),  _
 Global.System.Runtime.Serialization.DataContractAttribute(IsReference:=true),  _
 Global.System.Serializable()>  _
Partial Public Class Suppliers
    Inherits Global.System.Data.Objects.DataClasses.EntityObject
    '''<summary>
    '''Create a new Suppliers object.
    '''</summary>
    '''<param name="supplierID">Initial value of SupplierID.</param>
    '''<param name="companyName">Initial value of CompanyName.</param>
    Public Shared Function CreateSuppliers(ByVal supplierID As Integer, ByVal companyName As String) As Suppliers
        Dim suppliers As Suppliers = New Suppliers
        suppliers.SupplierID = supplierID
        suppliers.CompanyName = companyName
        Return suppliers
    End Function
    '''<summary>
    '''There are no comments for Property SupplierID in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property SupplierID() As Integer
        Get
            Return Me._SupplierID
        End Get
        Set
            Me.OnSupplierIDChanging(value)
            Me.ReportPropertyChanging("SupplierID")
            Me._SupplierID = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("SupplierID")
            Me.OnSupplierIDChanged
        End Set
    End Property
    Private _SupplierID As Integer
    Partial Private Sub OnSupplierIDChanging(ByVal value As Integer)
        End Sub
    Partial Private Sub OnSupplierIDChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property CompanyName in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property CompanyName() As String
        Get
            Return Me._CompanyName
        End Get
        Set
            Me.OnCompanyNameChanging(value)
            Me.ReportPropertyChanging("CompanyName")
            Me._CompanyName = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false)
            Me.ReportPropertyChanged("CompanyName")
            Me.OnCompanyNameChanged
        End Set
    End Property
    Private _CompanyName As String
    Partial Private Sub OnCompanyNameChanging(ByVal value As String)
        End Sub
    Partial Private Sub OnCompanyNameChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property ContactName in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property ContactName() As String
        Get
            Return Me._ContactName
        End Get
        Set
            Me.OnContactNameChanging(value)
            Me.ReportPropertyChanging("ContactName")
            Me._ContactName = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
            Me.ReportPropertyChanged("ContactName")
            Me.OnContactNameChanged
        End Set
    End Property
    Private _ContactName As String
    Partial Private Sub OnContactNameChanging(ByVal value As String)
        End Sub
    Partial Private Sub OnContactNameChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property ContactTitle in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property ContactTitle() As String
        Get
            Return Me._ContactTitle
        End Get
        Set
            Me.OnContactTitleChanging(value)
            Me.ReportPropertyChanging("ContactTitle")
            Me._ContactTitle = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
            Me.ReportPropertyChanged("ContactTitle")
            Me.OnContactTitleChanged
        End Set
    End Property
    Private _ContactTitle As String
    Partial Private Sub OnContactTitleChanging(ByVal value As String)
        End Sub
    Partial Private Sub OnContactTitleChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property Address in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Address() As String
        Get
            Return Me._Address
        End Get
        Set
            Me.OnAddressChanging(value)
            Me.ReportPropertyChanging("Address")
            Me._Address = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
            Me.ReportPropertyChanged("Address")
            Me.OnAddressChanged
        End Set
    End Property
    Private _Address As String
    Partial Private Sub OnAddressChanging(ByVal value As String)
        End Sub
    Partial Private Sub OnAddressChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property City in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property City() As String
        Get
            Return Me._City
        End Get
        Set
            Me.OnCityChanging(value)
            Me.ReportPropertyChanging("City")
            Me._City = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
            Me.ReportPropertyChanged("City")
            Me.OnCityChanged
        End Set
    End Property
    Private _City As String
    Partial Private Sub OnCityChanging(ByVal value As String)
        End Sub
    Partial Private Sub OnCityChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property Region in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Region() As String
        Get
            Return Me._Region
        End Get
        Set
            Me.OnRegionChanging(value)
            Me.ReportPropertyChanging("Region")
            Me._Region = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
            Me.ReportPropertyChanged("Region")
            Me.OnRegionChanged
        End Set
    End Property
    Private _Region As String
    Partial Private Sub OnRegionChanging(ByVal value As String)
        End Sub
    Partial Private Sub OnRegionChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property PostalCode in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property PostalCode() As String
        Get
            Return Me._PostalCode
        End Get
        Set
            Me.OnPostalCodeChanging(value)
            Me.ReportPropertyChanging("PostalCode")
            Me._PostalCode = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
            Me.ReportPropertyChanged("PostalCode")
            Me.OnPostalCodeChanged
        End Set
    End Property
    Private _PostalCode As String
    Partial Private Sub OnPostalCodeChanging(ByVal value As String)
        End Sub
    Partial Private Sub OnPostalCodeChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property Country in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Country() As String
        Get
            Return Me._Country
        End Get
        Set
            Me.OnCountryChanging(value)
            Me.ReportPropertyChanging("Country")
            Me._Country = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
            Me.ReportPropertyChanged("Country")
            Me.OnCountryChanged
        End Set
    End Property
    Private _Country As String
    Partial Private Sub OnCountryChanging(ByVal value As String)
        End Sub
    Partial Private Sub OnCountryChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property Phone in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Phone() As String
        Get
            Return Me._Phone
        End Get
        Set
            Me.OnPhoneChanging(value)
            Me.ReportPropertyChanging("Phone")
            Me._Phone = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
            Me.ReportPropertyChanged("Phone")
            Me.OnPhoneChanged
        End Set
    End Property
    Private _Phone As String
    Partial Private Sub OnPhoneChanging(ByVal value As String)
        End Sub
    Partial Private Sub OnPhoneChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property Fax in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Fax() As String
        Get
            Return Me._Fax
        End Get
        Set
            Me.OnFaxChanging(value)
            Me.ReportPropertyChanging("Fax")
            Me._Fax = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
            Me.ReportPropertyChanged("Fax")
            Me.OnFaxChanged
        End Set
    End Property
    Private _Fax As String
    Partial Private Sub OnFaxChanging(ByVal value As String)
        End Sub
    Partial Private Sub OnFaxChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property HomePage in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property HomePage() As String
        Get
            Return Me._HomePage
        End Get
        Set
            Me.OnHomePageChanging(value)
            Me.ReportPropertyChanging("HomePage")
            Me._HomePage = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
            Me.ReportPropertyChanged("HomePage")
            Me.OnHomePageChanged
        End Set
    End Property
    Private _HomePage As String
    Partial Private Sub OnHomePageChanging(ByVal value As String)
        End Sub
    Partial Private Sub OnHomePageChanged()
        End Sub
    '''<summary>
    '''There are no comments for Products in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("NorthwindModel", "FK_Products_Suppliers", "Products"),  _
     Global.System.Xml.Serialization.XmlIgnoreAttribute(),  _
     Global.System.Xml.Serialization.SoapIgnoreAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Products() As Global.System.Data.Objects.DataClasses.EntityCollection(Of Products)
        Get
            Return CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Products)("NorthwindModel.FK_Products_Suppliers", "Products")
        End Get
        Set
            If (Not (value) Is Nothing) Then
                CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Products)("NorthwindModel.FK_Products_Suppliers", "Products", value)
            End If
        End Set
    End Property
End Class
