Imports Microsoft.VisualBasic
Imports System
Namespace _03_Grouping
	Public Partial Class RadGridViewLab3
		''' <summary>
		''' Required designer variable.
		''' </summary>
		Private components As System.ComponentModel.IContainer = Nothing

		''' <summary>
		''' Clean up any resources being used.
		''' </summary>
		''' <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
		Protected Overrides Sub Dispose(ByVal disposing As Boolean)
			If disposing AndAlso (Not components Is Nothing) Then
				components.Dispose()
			End If
			MyBase.Dispose(disposing)
		End Sub

		#Region "Windows Form Designer generated code"

		''' <summary>
		''' Required method for Designer support - do not modify
		''' the contents of this method with the code editor.
		''' </summary>
		Private Sub InitializeComponent()
            Me.components = New System.ComponentModel.Container
            Dim GridViewTextBoxColumn1 As Telerik.WinControls.UI.GridViewTextBoxColumn = New Telerik.WinControls.UI.GridViewTextBoxColumn
            Dim GridViewTextBoxColumn2 As Telerik.WinControls.UI.GridViewTextBoxColumn = New Telerik.WinControls.UI.GridViewTextBoxColumn
            Dim GridViewTextBoxColumn3 As Telerik.WinControls.UI.GridViewTextBoxColumn = New Telerik.WinControls.UI.GridViewTextBoxColumn
            Dim GridViewTextBoxColumn4 As Telerik.WinControls.UI.GridViewTextBoxColumn = New Telerik.WinControls.UI.GridViewTextBoxColumn
            Dim GridViewTextBoxColumn5 As Telerik.WinControls.UI.GridViewTextBoxColumn = New Telerik.WinControls.UI.GridViewTextBoxColumn
            Dim GridViewTextBoxColumn6 As Telerik.WinControls.UI.GridViewTextBoxColumn = New Telerik.WinControls.UI.GridViewTextBoxColumn
            Dim GridViewTextBoxColumn7 As Telerik.WinControls.UI.GridViewTextBoxColumn = New Telerik.WinControls.UI.GridViewTextBoxColumn
            Dim GridViewTextBoxColumn8 As Telerik.WinControls.UI.GridViewTextBoxColumn = New Telerik.WinControls.UI.GridViewTextBoxColumn
            Dim GridViewTextBoxColumn9 As Telerik.WinControls.UI.GridViewTextBoxColumn = New Telerik.WinControls.UI.GridViewTextBoxColumn
            Dim GridViewTextBoxColumn10 As Telerik.WinControls.UI.GridViewTextBoxColumn = New Telerik.WinControls.UI.GridViewTextBoxColumn
            Dim GridViewTextBoxColumn11 As Telerik.WinControls.UI.GridViewTextBoxColumn = New Telerik.WinControls.UI.GridViewTextBoxColumn
            Dim GroupDescriptor1 As Telerik.WinControls.Data.GroupDescriptor = New Telerik.WinControls.Data.GroupDescriptor
            Dim SortDescriptor1 As Telerik.WinControls.Data.SortDescriptor = New Telerik.WinControls.Data.SortDescriptor
            Dim GroupDescriptor2 As Telerik.WinControls.Data.GroupDescriptor = New Telerik.WinControls.Data.GroupDescriptor
            Dim SortDescriptor2 As Telerik.WinControls.Data.SortDescriptor = New Telerik.WinControls.Data.SortDescriptor
            Dim SortDescriptor3 As Telerik.WinControls.Data.SortDescriptor = New Telerik.WinControls.Data.SortDescriptor
            Dim SortDescriptor4 As Telerik.WinControls.Data.SortDescriptor = New Telerik.WinControls.Data.SortDescriptor
            Me.radGridView1 = New Telerik.WinControls.UI.RadGridView
            Me.customersBindingSource = New System.Windows.Forms.BindingSource(Me.components)
            Me.dataSet1 = New DataSet1
            Me.customersTableAdapter = New DataSet1TableAdapters.CustomersTableAdapter
            CType(Me.radGridView1, System.ComponentModel.ISupportInitialize).BeginInit()
            CType(Me.radGridView1.MasterTemplate, System.ComponentModel.ISupportInitialize).BeginInit()
            CType(Me.customersBindingSource, System.ComponentModel.ISupportInitialize).BeginInit()
            CType(Me.dataSet1, System.ComponentModel.ISupportInitialize).BeginInit()
            Me.SuspendLayout()
            '
            'radGridView1
            '
            Me.radGridView1.BackColor = System.Drawing.SystemColors.Control
            Me.radGridView1.Cursor = System.Windows.Forms.Cursors.Default
            Me.radGridView1.Dock = System.Windows.Forms.DockStyle.Fill
            Me.radGridView1.Font = New System.Drawing.Font("Microsoft Sans Serif", 8.25!)
            Me.radGridView1.ForeColor = System.Drawing.SystemColors.ControlText
            Me.radGridView1.ImeMode = System.Windows.Forms.ImeMode.NoControl
            Me.radGridView1.Location = New System.Drawing.Point(0, 0)
            '
            'radGridView1
            '
            Me.radGridView1.MasterTemplate.AutoSizeColumnsMode = Telerik.WinControls.UI.GridViewAutoSizeColumnsMode.Fill
            GridViewTextBoxColumn1.FieldName = "CustomerID"
            GridViewTextBoxColumn1.HeaderText = "CustomerID"
            GridViewTextBoxColumn1.IsAutoGenerated = True
            GridViewTextBoxColumn1.IsVisible = False
            GridViewTextBoxColumn1.Name = "CustomerID"
            GridViewTextBoxColumn2.FieldName = "CompanyName"
            GridViewTextBoxColumn2.HeaderText = "CompanyName"
            GridViewTextBoxColumn2.IsAutoGenerated = True
            GridViewTextBoxColumn2.Name = "CompanyName"
            GridViewTextBoxColumn2.Width = 130
            GridViewTextBoxColumn3.FieldName = "ContactName"
            GridViewTextBoxColumn3.HeaderText = "ContactName"
            GridViewTextBoxColumn3.IsAutoGenerated = True
            GridViewTextBoxColumn3.Name = "ContactName"
            GridViewTextBoxColumn3.Width = 130
            GridViewTextBoxColumn4.FieldName = "ContactTitle"
            GridViewTextBoxColumn4.HeaderText = "ContactTitle"
            GridViewTextBoxColumn4.IsAutoGenerated = True
            GridViewTextBoxColumn4.Name = "ContactTitle"
            GridViewTextBoxColumn4.Width = 130
            GridViewTextBoxColumn5.FieldName = "Address"
            GridViewTextBoxColumn5.HeaderText = "Address"
            GridViewTextBoxColumn5.IsAutoGenerated = True
            GridViewTextBoxColumn5.Name = "Address"
            GridViewTextBoxColumn5.Width = 130
            GridViewTextBoxColumn6.FieldName = "City"
            GridViewTextBoxColumn6.HeaderText = "City"
            GridViewTextBoxColumn6.IsAutoGenerated = True
            GridViewTextBoxColumn6.Name = "City"
            GridViewTextBoxColumn6.Width = 86
            GridViewTextBoxColumn7.FieldName = "Region"
            GridViewTextBoxColumn7.HeaderText = "Region"
            GridViewTextBoxColumn7.IsAutoGenerated = True
            GridViewTextBoxColumn7.IsVisible = False
            GridViewTextBoxColumn7.Name = "Region"
            GridViewTextBoxColumn8.FieldName = "PostalCode"
            GridViewTextBoxColumn8.HeaderText = "PostalCode"
            GridViewTextBoxColumn8.IsAutoGenerated = True
            GridViewTextBoxColumn8.Name = "PostalCode"
            GridViewTextBoxColumn8.Width = 149
            GridViewTextBoxColumn9.FieldName = "Country"
            GridViewTextBoxColumn9.HeaderText = "Country"
            GridViewTextBoxColumn9.IsAutoGenerated = True
            GridViewTextBoxColumn9.Name = "Country"
            GridViewTextBoxColumn9.Width = 60
            GridViewTextBoxColumn10.FieldName = "Phone"
            GridViewTextBoxColumn10.HeaderText = "Phone"
            GridViewTextBoxColumn10.IsAutoGenerated = True
            GridViewTextBoxColumn10.IsVisible = False
            GridViewTextBoxColumn10.Name = "Phone"
            GridViewTextBoxColumn11.FieldName = "Fax"
            GridViewTextBoxColumn11.HeaderText = "Fax"
            GridViewTextBoxColumn11.IsAutoGenerated = True
            GridViewTextBoxColumn11.IsVisible = False
            GridViewTextBoxColumn11.Name = "Fax"
            Me.radGridView1.MasterTemplate.Columns.AddRange(New Telerik.WinControls.UI.GridViewDataColumn() {GridViewTextBoxColumn1, GridViewTextBoxColumn2, GridViewTextBoxColumn3, GridViewTextBoxColumn4, GridViewTextBoxColumn5, GridViewTextBoxColumn6, GridViewTextBoxColumn7, GridViewTextBoxColumn8, GridViewTextBoxColumn9, GridViewTextBoxColumn10, GridViewTextBoxColumn11})
            Me.radGridView1.MasterTemplate.DataSource = Me.customersBindingSource
            SortDescriptor1.Direction = System.ComponentModel.ListSortDirection.Descending
            SortDescriptor1.PropertyName = "Country"
            GroupDescriptor1.GroupNames.AddRange(New Telerik.WinControls.Data.SortDescriptor() {SortDescriptor1})
            SortDescriptor2.PropertyName = "City"
            GroupDescriptor2.GroupNames.AddRange(New Telerik.WinControls.Data.SortDescriptor() {SortDescriptor2})
            Me.radGridView1.MasterTemplate.GroupDescriptors.AddRange(New Telerik.WinControls.Data.GroupDescriptor() {GroupDescriptor1, GroupDescriptor2})
            SortDescriptor3.PropertyName = "City"
            SortDescriptor4.Direction = System.ComponentModel.ListSortDirection.Descending
            SortDescriptor4.PropertyName = "Country"
            Me.radGridView1.MasterTemplate.SortDescriptors.AddRange(New Telerik.WinControls.Data.SortDescriptor() {SortDescriptor3, SortDescriptor4})
            Me.radGridView1.Name = "radGridView1"
            Me.radGridView1.RightToLeft = System.Windows.Forms.RightToLeft.No
            Me.radGridView1.Size = New System.Drawing.Size(728, 398)
            Me.radGridView1.TabIndex = 0
            Me.radGridView1.Text = "radGridViewPreview"
            '
            'customersBindingSource
            '
            Me.customersBindingSource.DataMember = "Customers"
            Me.customersBindingSource.DataSource = Me.dataSet1
            '
            'dataSet1
            '
            Me.dataSet1.DataSetName = "DataSet1"
            Me.dataSet1.SchemaSerializationMode = System.Data.SchemaSerializationMode.IncludeSchema
            '
            'customersTableAdapter
            '
            Me.customersTableAdapter.ClearBeforeFill = True
            '
            'RadGridViewLab3
            '
            Me.AutoScaleDimensions = New System.Drawing.SizeF(6.0!, 13.0!)
            Me.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font
            Me.ClientSize = New System.Drawing.Size(728, 398)
            Me.Controls.Add(Me.radGridView1)
            Me.Name = "RadGridViewLab3"
            Me.Text = "RadGridView Lab 3"
            CType(Me.radGridView1.MasterTemplate, System.ComponentModel.ISupportInitialize).EndInit()
            CType(Me.radGridView1, System.ComponentModel.ISupportInitialize).EndInit()
            CType(Me.customersBindingSource, System.ComponentModel.ISupportInitialize).EndInit()
            CType(Me.dataSet1, System.ComponentModel.ISupportInitialize).EndInit()
            Me.ResumeLayout(False)

        End Sub

		#End Region

		Private radGridView1 As Telerik.WinControls.UI.RadGridView
		Private dataSet1 As DataSet1
		Private customersBindingSource As System.Windows.Forms.BindingSource
        Private customersTableAdapter As DataSet1TableAdapters.CustomersTableAdapter
        Private WithEvents MasterTemplate As Telerik.WinControls.UI.RadGridView
	End Class
End Namespace

