namespace _02_AddingColumns
{
    partial class RadGridViewLab2
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Telerik.WinControls.UI.GridViewDecimalColumn gridViewDecimalColumn17 = new Telerik.WinControls.UI.GridViewDecimalColumn();
            Telerik.WinControls.UI.GridViewDecimalColumn gridViewDecimalColumn18 = new Telerik.WinControls.UI.GridViewDecimalColumn();
            Telerik.WinControls.UI.GridViewDecimalColumn gridViewDecimalColumn19 = new Telerik.WinControls.UI.GridViewDecimalColumn();
            Telerik.WinControls.UI.GridViewDecimalColumn gridViewDecimalColumn20 = new Telerik.WinControls.UI.GridViewDecimalColumn();
            Telerik.WinControls.UI.GridViewDecimalColumn gridViewDecimalColumn21 = new Telerik.WinControls.UI.GridViewDecimalColumn();
            Telerik.WinControls.UI.GridViewDecimalColumn gridViewDecimalColumn22 = new Telerik.WinControls.UI.GridViewDecimalColumn();
            Telerik.WinControls.UI.GridViewDecimalColumn gridViewDecimalColumn23 = new Telerik.WinControls.UI.GridViewDecimalColumn();
            Telerik.WinControls.UI.GridViewTextBoxColumn gridViewTextBoxColumn3 = new Telerik.WinControls.UI.GridViewTextBoxColumn();
            Telerik.WinControls.UI.GridViewDateTimeColumn gridViewDateTimeColumn3 = new Telerik.WinControls.UI.GridViewDateTimeColumn();
            Telerik.WinControls.UI.GridViewDecimalColumn gridViewDecimalColumn24 = new Telerik.WinControls.UI.GridViewDecimalColumn();
            this.radGridView1 = new Telerik.WinControls.UI.RadGridView();
            this.salesPersonBindingSource = new System.Windows.Forms.BindingSource(this.components);
            this.adventureWorksDataSet = new _02_AddingColumns.AdventureWorksDataSet();
            this.salesPersonTableAdapter = new _02_AddingColumns.AdventureWorksDataSetTableAdapters.SalesPersonTableAdapter();
            ((System.ComponentModel.ISupportInitialize)(this.radGridView1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.radGridView1.MasterTemplate)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.salesPersonBindingSource)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.adventureWorksDataSet)).BeginInit();
            this.SuspendLayout();
            // 
            // radGridView1
            // 
            this.radGridView1.BackColor = System.Drawing.SystemColors.Control;
            this.radGridView1.Cursor = System.Windows.Forms.Cursors.Default;
            this.radGridView1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.radGridView1.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F);
            this.radGridView1.ForeColor = System.Drawing.SystemColors.ControlText;
            this.radGridView1.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            this.radGridView1.Location = new System.Drawing.Point(0, 0);
            // 
            // radGridView1
            // 
            this.radGridView1.MasterTemplate.Caption = "SalesPerson";
            gridViewDecimalColumn17.DataType = typeof(int);
            gridViewDecimalColumn17.FieldName = "SalesPersonID";
            gridViewDecimalColumn17.FormatString = "";
            gridViewDecimalColumn17.HeaderText = "ID";
            gridViewDecimalColumn17.IsAutoGenerated = true;
            gridViewDecimalColumn17.Name = "SalesPersonID";
            gridViewDecimalColumn17.TextAlignment = System.Drawing.ContentAlignment.MiddleRight;
            gridViewDecimalColumn17.Width = 120;
            gridViewDecimalColumn18.DataType = typeof(int);
            gridViewDecimalColumn18.FieldName = "TerritoryID";
            gridViewDecimalColumn18.HeaderText = "TerritoryID";
            gridViewDecimalColumn18.IsAutoGenerated = true;
            gridViewDecimalColumn18.IsVisible = false;
            gridViewDecimalColumn18.Name = "TerritoryID";
            gridViewDecimalColumn18.TextAlignment = System.Drawing.ContentAlignment.MiddleRight;
            gridViewDecimalColumn18.Width = 133;
            gridViewDecimalColumn19.FieldName = "SalesQuota";
            gridViewDecimalColumn19.FormatString = "";
            gridViewDecimalColumn19.HeaderText = "Quota";
            gridViewDecimalColumn19.IsAutoGenerated = true;
            gridViewDecimalColumn19.Name = "SalesQuota";
            gridViewDecimalColumn19.TextAlignment = System.Drawing.ContentAlignment.MiddleRight;
            gridViewDecimalColumn19.Width = 120;
            gridViewDecimalColumn20.FieldName = "Bonus";
            gridViewDecimalColumn20.FormatString = "";
            gridViewDecimalColumn20.HeaderText = "Bonus";
            gridViewDecimalColumn20.IsAutoGenerated = true;
            gridViewDecimalColumn20.Name = "Bonus";
            gridViewDecimalColumn20.TextAlignment = System.Drawing.ContentAlignment.MiddleRight;
            gridViewDecimalColumn20.Width = 120;
            gridViewDecimalColumn21.FieldName = "CommissionPct";
            gridViewDecimalColumn21.FormatString = "";
            gridViewDecimalColumn21.HeaderText = "Commission Pct";
            gridViewDecimalColumn21.IsAutoGenerated = true;
            gridViewDecimalColumn21.Name = "CommissionPct";
            gridViewDecimalColumn21.TextAlignment = System.Drawing.ContentAlignment.MiddleRight;
            gridViewDecimalColumn21.Width = 120;
            gridViewDecimalColumn22.FieldName = "SalesYTD";
            gridViewDecimalColumn22.FormatString = "";
            gridViewDecimalColumn22.HeaderText = "YTD";
            gridViewDecimalColumn22.IsAutoGenerated = true;
            gridViewDecimalColumn22.Name = "SalesYTD";
            gridViewDecimalColumn22.TextAlignment = System.Drawing.ContentAlignment.MiddleRight;
            gridViewDecimalColumn22.Width = 120;
            gridViewDecimalColumn23.FieldName = "SalesLastYear";
            gridViewDecimalColumn23.FormatString = "";
            gridViewDecimalColumn23.HeaderText = "Sales Last Year";
            gridViewDecimalColumn23.IsAutoGenerated = true;
            gridViewDecimalColumn23.Name = "SalesLastYear";
            gridViewDecimalColumn23.TextAlignment = System.Drawing.ContentAlignment.MiddleRight;
            gridViewDecimalColumn23.Width = 120;
            gridViewTextBoxColumn3.DataType = typeof(System.Guid);
            gridViewTextBoxColumn3.FieldName = "rowguid";
            gridViewTextBoxColumn3.HeaderText = "rowguid";
            gridViewTextBoxColumn3.IsAutoGenerated = true;
            gridViewTextBoxColumn3.IsVisible = false;
            gridViewTextBoxColumn3.Name = "rowguid";
            gridViewTextBoxColumn3.Width = 116;
            gridViewDateTimeColumn3.FieldName = "ModifiedDate";
            gridViewDateTimeColumn3.HeaderText = "ModifiedDate";
            gridViewDateTimeColumn3.IsAutoGenerated = true;
            gridViewDateTimeColumn3.IsVisible = false;
            gridViewDateTimeColumn3.Name = "ModifiedDate";
            gridViewDateTimeColumn3.Width = 103;
            gridViewDecimalColumn24.FormatString = "";
            gridViewDecimalColumn24.HeaderText = "Percent of Quota";
            gridViewDecimalColumn24.Name = "PercentQuota";
            gridViewDecimalColumn24.TextAlignment = System.Drawing.ContentAlignment.MiddleRight;
            gridViewDecimalColumn24.Width = 37;
            this.radGridView1.MasterTemplate.Columns.AddRange(new Telerik.WinControls.UI.GridViewDataColumn[] {
            gridViewDecimalColumn17,
            gridViewDecimalColumn18,
            gridViewDecimalColumn19,
            gridViewDecimalColumn20,
            gridViewDecimalColumn21,
            gridViewDecimalColumn22,
            gridViewDecimalColumn23,
            gridViewTextBoxColumn3,
            gridViewDateTimeColumn3,
            gridViewDecimalColumn24});
            this.radGridView1.MasterTemplate.DataSource = this.salesPersonBindingSource;
            this.radGridView1.Name = "radGridView1";
            this.radGridView1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.radGridView1.Size = new System.Drawing.Size(784, 357);
            this.radGridView1.TabIndex = 0;
            this.radGridView1.Text = "radGridViewPreview";
            this.radGridView1.ThemeName = "ControlDefault";
            // 
            // salesPersonBindingSource
            // 
            this.salesPersonBindingSource.DataMember = "SalesPerson";
            this.salesPersonBindingSource.DataSource = this.adventureWorksDataSet;
            // 
            // adventureWorksDataSet
            // 
            this.adventureWorksDataSet.DataSetName = "AdventureWorksDataSet";
            this.adventureWorksDataSet.SchemaSerializationMode = System.Data.SchemaSerializationMode.IncludeSchema;
            // 
            // salesPersonTableAdapter
            // 
            this.salesPersonTableAdapter.ClearBeforeFill = true;
            // 
            // RadGridViewLab2
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(784, 357);
            this.Controls.Add(this.radGridView1);
            this.Name = "RadGridViewLab2";
            this.Text = "RadGridView Lab 2";
            this.Load += new System.EventHandler(this.RadGridViewLab2_Load);
            ((System.ComponentModel.ISupportInitialize)(this.radGridView1.MasterTemplate)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.radGridView1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.salesPersonBindingSource)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.adventureWorksDataSet)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Telerik.WinControls.UI.RadGridView radGridView1;
        private AdventureWorksDataSet adventureWorksDataSet;
        private System.Windows.Forms.BindingSource salesPersonBindingSource;
        private _02_AddingColumns.AdventureWorksDataSetTableAdapters.SalesPersonTableAdapter salesPersonTableAdapter;
    }
}

