Imports Microsoft.VisualBasic
Imports System
Namespace _05_HierarchyDesigner
	Public Partial Class RadGridViewLab5
		''' <summary>
		''' Required designer variable.
		''' </summary>
		Private components As System.ComponentModel.IContainer = Nothing

		''' <summary>
		''' Clean up any resources being used.
		''' </summary>
		''' <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
		Protected Overrides Sub Dispose(ByVal disposing As Boolean)
			If disposing AndAlso (Not components Is Nothing) Then
				components.Dispose()
			End If
			MyBase.Dispose(disposing)
		End Sub

		#Region "Windows Form Designer generated code"

		''' <summary>
		''' Required method for Designer support - do not modify
		''' the contents of this method with the code editor.
		''' </summary>
		Private Sub InitializeComponent()
            Me.components = New System.ComponentModel.Container
            Dim GridViewDecimalColumn1 As Telerik.WinControls.UI.GridViewDecimalColumn = New Telerik.WinControls.UI.GridViewDecimalColumn
            Dim GridViewDecimalColumn2 As Telerik.WinControls.UI.GridViewDecimalColumn = New Telerik.WinControls.UI.GridViewDecimalColumn
            Dim GridViewDecimalColumn3 As Telerik.WinControls.UI.GridViewDecimalColumn = New Telerik.WinControls.UI.GridViewDecimalColumn
            Dim GridViewDateTimeColumn1 As Telerik.WinControls.UI.GridViewDateTimeColumn = New Telerik.WinControls.UI.GridViewDateTimeColumn
            Dim GridViewDateTimeColumn2 As Telerik.WinControls.UI.GridViewDateTimeColumn = New Telerik.WinControls.UI.GridViewDateTimeColumn
            Dim GridViewDateTimeColumn3 As Telerik.WinControls.UI.GridViewDateTimeColumn = New Telerik.WinControls.UI.GridViewDateTimeColumn
            Dim GridViewDecimalColumn4 As Telerik.WinControls.UI.GridViewDecimalColumn = New Telerik.WinControls.UI.GridViewDecimalColumn
            Dim GridViewTextBoxColumn1 As Telerik.WinControls.UI.GridViewTextBoxColumn = New Telerik.WinControls.UI.GridViewTextBoxColumn
            Dim GridViewTextBoxColumn2 As Telerik.WinControls.UI.GridViewTextBoxColumn = New Telerik.WinControls.UI.GridViewTextBoxColumn
            Dim GridViewDateTimeColumn4 As Telerik.WinControls.UI.GridViewDateTimeColumn = New Telerik.WinControls.UI.GridViewDateTimeColumn
            Dim GridViewRelation1 As Telerik.WinControls.UI.GridViewRelation = New Telerik.WinControls.UI.GridViewRelation
            Dim resources As System.ComponentModel.ComponentResourceManager = New System.ComponentModel.ComponentResourceManager(GetType(RadGridViewLab5))
            Me.gridViewTemplate1 = New Telerik.WinControls.UI.GridViewTemplate
            Me.employeeDepartmentHistoryBindingSource = New System.Windows.Forms.BindingSource(Me.components)
            Me.adventureWorksDataSet1 = New AdventureWorksDataSet1
            Me.MasterTemplate = New Telerik.WinControls.UI.RadGridView
            Me.departmentBindingSource = New System.Windows.Forms.BindingSource(Me.components)
            Me.departmentTableAdapter = New AdventureWorksDataSet1TableAdapters.DepartmentTableAdapter
            Me.employeeDepartmentHistoryTableAdapter = New AdventureWorksDataSet1TableAdapters.EmployeeDepartmentHistoryTableAdapter
            CType(Me.gridViewTemplate1, System.ComponentModel.ISupportInitialize).BeginInit()
            CType(Me.employeeDepartmentHistoryBindingSource, System.ComponentModel.ISupportInitialize).BeginInit()
            CType(Me.adventureWorksDataSet1, System.ComponentModel.ISupportInitialize).BeginInit()
            CType(Me.MasterTemplate, System.ComponentModel.ISupportInitialize).BeginInit()
            CType(Me.MasterTemplate.MasterTemplate, System.ComponentModel.ISupportInitialize).BeginInit()
            CType(Me.departmentBindingSource, System.ComponentModel.ISupportInitialize).BeginInit()
            Me.SuspendLayout()
            '
            'gridViewTemplate1
            '
            Me.gridViewTemplate1.AllowAddNewRow = False
            Me.gridViewTemplate1.AutoSizeColumnsMode = Telerik.WinControls.UI.GridViewAutoSizeColumnsMode.Fill
            GridViewDecimalColumn1.DataType = GetType(Integer)
            GridViewDecimalColumn1.FieldName = "EmployeeID"
            GridViewDecimalColumn1.FormatInfo = New System.Globalization.CultureInfo("")
            GridViewDecimalColumn1.HeaderText = "EmployeeID"
            GridViewDecimalColumn1.IsAutoGenerated = True
            GridViewDecimalColumn1.Name = "EmployeeID"
            GridViewDecimalColumn1.TextAlignment = System.Drawing.ContentAlignment.MiddleRight
            GridViewDecimalColumn2.DataType = GetType(Short)
            GridViewDecimalColumn2.FieldName = "DepartmentID"
            GridViewDecimalColumn2.FormatInfo = New System.Globalization.CultureInfo("")
            GridViewDecimalColumn2.HeaderText = "DepartmentID"
            GridViewDecimalColumn2.IsAutoGenerated = True
            GridViewDecimalColumn2.Name = "DepartmentID"
            GridViewDecimalColumn2.TextAlignment = System.Drawing.ContentAlignment.MiddleRight
            GridViewDecimalColumn3.DataType = GetType(Byte)
            GridViewDecimalColumn3.FieldName = "ShiftID"
            GridViewDecimalColumn3.FormatInfo = New System.Globalization.CultureInfo("")
            GridViewDecimalColumn3.HeaderText = "ShiftID"
            GridViewDecimalColumn3.IsAutoGenerated = True
            GridViewDecimalColumn3.Name = "ShiftID"
            GridViewDecimalColumn3.TextAlignment = System.Drawing.ContentAlignment.MiddleRight
            GridViewDateTimeColumn1.FieldName = "StartDate"
            GridViewDateTimeColumn1.Format = System.Windows.Forms.DateTimePickerFormat.[Long]
            GridViewDateTimeColumn1.FormatInfo = New System.Globalization.CultureInfo("")
            GridViewDateTimeColumn1.HeaderText = "StartDate"
            GridViewDateTimeColumn1.IsAutoGenerated = True
            GridViewDateTimeColumn1.Name = "StartDate"
            GridViewDateTimeColumn2.FieldName = "EndDate"
            GridViewDateTimeColumn2.Format = System.Windows.Forms.DateTimePickerFormat.[Long]
            GridViewDateTimeColumn2.FormatInfo = New System.Globalization.CultureInfo("")
            GridViewDateTimeColumn2.HeaderText = "EndDate"
            GridViewDateTimeColumn2.IsAutoGenerated = True
            GridViewDateTimeColumn2.Name = "EndDate"
            GridViewDateTimeColumn3.FieldName = "ModifiedDate"
            GridViewDateTimeColumn3.Format = System.Windows.Forms.DateTimePickerFormat.[Long]
            GridViewDateTimeColumn3.FormatInfo = New System.Globalization.CultureInfo("")
            GridViewDateTimeColumn3.HeaderText = "ModifiedDate"
            GridViewDateTimeColumn3.IsAutoGenerated = True
            GridViewDateTimeColumn3.Name = "ModifiedDate"
            Me.gridViewTemplate1.Columns.AddRange(New Telerik.WinControls.UI.GridViewDataColumn() {GridViewDecimalColumn1, GridViewDecimalColumn2, GridViewDecimalColumn3, GridViewDateTimeColumn1, GridViewDateTimeColumn2, GridViewDateTimeColumn3})
            Me.gridViewTemplate1.DataSource = Me.employeeDepartmentHistoryBindingSource
            '
            'employeeDepartmentHistoryBindingSource
            '
            Me.employeeDepartmentHistoryBindingSource.DataMember = "EmployeeDepartmentHistory"
            Me.employeeDepartmentHistoryBindingSource.DataSource = Me.adventureWorksDataSet1
            '
            'adventureWorksDataSet1
            '
            Me.adventureWorksDataSet1.DataSetName = "AdventureWorksDataSet1"
            Me.adventureWorksDataSet1.SchemaSerializationMode = System.Data.SchemaSerializationMode.IncludeSchema
            '
            'MasterTemplate
            '
            Me.MasterTemplate.BackColor = System.Drawing.SystemColors.Control
            Me.MasterTemplate.Cursor = System.Windows.Forms.Cursors.Default
            Me.MasterTemplate.Dock = System.Windows.Forms.DockStyle.Fill
            Me.MasterTemplate.Font = New System.Drawing.Font("Microsoft Sans Serif", 8.25!)
            Me.MasterTemplate.ForeColor = System.Drawing.SystemColors.ControlText
            Me.MasterTemplate.ImeMode = System.Windows.Forms.ImeMode.NoControl
            Me.MasterTemplate.Location = New System.Drawing.Point(0, 0)
            '
            'MasterTemplate
            '
            Me.MasterTemplate.MasterTemplate.AddNewRowPosition = Telerik.WinControls.UI.SystemRowPosition.Bottom
            Me.MasterTemplate.MasterTemplate.AllowAddNewRow = False
            Me.MasterTemplate.MasterTemplate.AutoSizeColumnsMode = Telerik.WinControls.UI.GridViewAutoSizeColumnsMode.Fill
            GridViewDecimalColumn4.DataType = GetType(Short)
            GridViewDecimalColumn4.FieldName = "DepartmentID"
            GridViewDecimalColumn4.FormatInfo = New System.Globalization.CultureInfo("")
            GridViewDecimalColumn4.HeaderText = "DepartmentID"
            GridViewDecimalColumn4.IsAutoGenerated = True
            GridViewDecimalColumn4.Name = "DepartmentID"
            GridViewDecimalColumn4.ReadOnly = True
            GridViewDecimalColumn4.TextAlignment = System.Drawing.ContentAlignment.MiddleRight
            GridViewDecimalColumn4.Width = 192
            GridViewTextBoxColumn1.FieldName = "Name"
            GridViewTextBoxColumn1.FormatInfo = New System.Globalization.CultureInfo("")
            GridViewTextBoxColumn1.HeaderText = "Name"
            GridViewTextBoxColumn1.IsAutoGenerated = True
            GridViewTextBoxColumn1.Name = "Name"
            GridViewTextBoxColumn1.Width = 192
            GridViewTextBoxColumn2.FieldName = "GroupName"
            GridViewTextBoxColumn2.FormatInfo = New System.Globalization.CultureInfo("")
            GridViewTextBoxColumn2.HeaderText = "GroupName"
            GridViewTextBoxColumn2.IsAutoGenerated = True
            GridViewTextBoxColumn2.Name = "GroupName"
            GridViewTextBoxColumn2.Width = 192
            GridViewDateTimeColumn4.FieldName = "ModifiedDate"
            GridViewDateTimeColumn4.Format = System.Windows.Forms.DateTimePickerFormat.[Long]
            GridViewDateTimeColumn4.FormatInfo = New System.Globalization.CultureInfo("")
            GridViewDateTimeColumn4.HeaderText = "ModifiedDate"
            GridViewDateTimeColumn4.IsAutoGenerated = True
            GridViewDateTimeColumn4.Name = "ModifiedDate"
            GridViewDateTimeColumn4.Width = 196
            Me.MasterTemplate.MasterTemplate.Columns.AddRange(New Telerik.WinControls.UI.GridViewDataColumn() {GridViewDecimalColumn4, GridViewTextBoxColumn1, GridViewTextBoxColumn2, GridViewDateTimeColumn4})
            Me.MasterTemplate.MasterTemplate.DataSource = Me.departmentBindingSource
            Me.MasterTemplate.MasterTemplate.Templates.AddRange(New Telerik.WinControls.UI.GridViewTemplate() {Me.gridViewTemplate1})
            Me.MasterTemplate.Name = "MasterTemplate"
            GridViewRelation1.ChildColumnNames = CType(resources.GetObject("GridViewRelation1.ChildColumnNames"), System.Collections.Specialized.StringCollection)
            GridViewRelation1.ChildTemplate = Me.gridViewTemplate1
            GridViewRelation1.ParentColumnNames = CType(resources.GetObject("GridViewRelation1.ParentColumnNames"), System.Collections.Specialized.StringCollection)
            GridViewRelation1.ParentTemplate = Me.MasterTemplate.MasterTemplate
            GridViewRelation1.RelationName = "DepartmenttoDepartmentHistory"
            Me.MasterTemplate.Relations.AddRange(New Telerik.WinControls.UI.GridViewRelation() {GridViewRelation1})
            Me.MasterTemplate.RightToLeft = System.Windows.Forms.RightToLeft.No
            Me.MasterTemplate.Size = New System.Drawing.Size(811, 342)
            Me.MasterTemplate.TabIndex = 0
            Me.MasterTemplate.Text = "radGridViewPreview"
            Me.MasterTemplate.ThemeName = "ControlDefault"
            '
            'departmentBindingSource
            '
            Me.departmentBindingSource.DataMember = "Department"
            Me.departmentBindingSource.DataSource = Me.adventureWorksDataSet1
            '
            'departmentTableAdapter
            '
            Me.departmentTableAdapter.ClearBeforeFill = True
            '
            'employeeDepartmentHistoryTableAdapter
            '
            Me.employeeDepartmentHistoryTableAdapter.ClearBeforeFill = True
            '
            'RadGridViewLab5
            '
            Me.AutoScaleDimensions = New System.Drawing.SizeF(6.0!, 13.0!)
            Me.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font
            Me.ClientSize = New System.Drawing.Size(811, 342)
            Me.Controls.Add(Me.MasterTemplate)
            Me.Name = "RadGridViewLab5"
            Me.Text = "RadGridView Lab 5"
            CType(Me.gridViewTemplate1, System.ComponentModel.ISupportInitialize).EndInit()
            CType(Me.employeeDepartmentHistoryBindingSource, System.ComponentModel.ISupportInitialize).EndInit()
            CType(Me.adventureWorksDataSet1, System.ComponentModel.ISupportInitialize).EndInit()
            CType(Me.MasterTemplate.MasterTemplate, System.ComponentModel.ISupportInitialize).EndInit()
            CType(Me.MasterTemplate, System.ComponentModel.ISupportInitialize).EndInit()
            CType(Me.departmentBindingSource, System.ComponentModel.ISupportInitialize).EndInit()
            Me.ResumeLayout(False)

        End Sub

		#End Region

		Private radGridView1 As Telerik.WinControls.UI.RadGridView
		Private adventureWorksDataSet1 As AdventureWorksDataSet1
		Private departmentBindingSource As System.Windows.Forms.BindingSource
        Private departmentTableAdapter As AdventureWorksDataSet1TableAdapters.DepartmentTableAdapter
		Private employeeDepartmentHistoryBindingSource As System.Windows.Forms.BindingSource
        Private employeeDepartmentHistoryTableAdapter As AdventureWorksDataSet1TableAdapters.EmployeeDepartmentHistoryTableAdapter
        Private gridViewTemplate1 As Telerik.WinControls.UI.GridViewTemplate
        Private WithEvents MasterTemplate As Telerik.WinControls.UI.RadGridView
	End Class
End Namespace

