Imports Microsoft.VisualBasic
Imports System
Namespace _02_AddingColumns
	Public Partial Class RadGridViewLab2
		''' <summary>
		''' Required designer variable.
		''' </summary>
		Private components As System.ComponentModel.IContainer = Nothing

		''' <summary>
		''' Clean up any resources being used.
		''' </summary>
		''' <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
		Protected Overrides Sub Dispose(ByVal disposing As Boolean)
			If disposing AndAlso (Not components Is Nothing) Then
				components.Dispose()
			End If
			MyBase.Dispose(disposing)
		End Sub

		#Region "Windows Form Designer generated code"

		''' <summary>
		''' Required method for Designer support - do not modify
		''' the contents of this method with the code editor.
		''' </summary>
		Private Sub InitializeComponent()
            Me.components = New System.ComponentModel.Container
            Dim GridViewDecimalColumn1 As Telerik.WinControls.UI.GridViewDecimalColumn = New Telerik.WinControls.UI.GridViewDecimalColumn
            Dim GridViewDecimalColumn2 As Telerik.WinControls.UI.GridViewDecimalColumn = New Telerik.WinControls.UI.GridViewDecimalColumn
            Dim GridViewDecimalColumn3 As Telerik.WinControls.UI.GridViewDecimalColumn = New Telerik.WinControls.UI.GridViewDecimalColumn
            Dim GridViewDecimalColumn4 As Telerik.WinControls.UI.GridViewDecimalColumn = New Telerik.WinControls.UI.GridViewDecimalColumn
            Dim GridViewDecimalColumn5 As Telerik.WinControls.UI.GridViewDecimalColumn = New Telerik.WinControls.UI.GridViewDecimalColumn
            Dim GridViewDecimalColumn6 As Telerik.WinControls.UI.GridViewDecimalColumn = New Telerik.WinControls.UI.GridViewDecimalColumn
            Dim GridViewDecimalColumn7 As Telerik.WinControls.UI.GridViewDecimalColumn = New Telerik.WinControls.UI.GridViewDecimalColumn
            Dim GridViewTextBoxColumn1 As Telerik.WinControls.UI.GridViewTextBoxColumn = New Telerik.WinControls.UI.GridViewTextBoxColumn
            Dim GridViewDateTimeColumn1 As Telerik.WinControls.UI.GridViewDateTimeColumn = New Telerik.WinControls.UI.GridViewDateTimeColumn
            Dim GridViewDecimalColumn8 As Telerik.WinControls.UI.GridViewDecimalColumn = New Telerik.WinControls.UI.GridViewDecimalColumn
            Me.radGridView1 = New Telerik.WinControls.UI.RadGridView
            Me.salesPersonBindingSource = New System.Windows.Forms.BindingSource(Me.components)
            Me.adventureWorksDataSet = New AdventureWorksDataSet
            Me.salesPersonTableAdapter = New AdventureWorksDataSetTableAdapters.SalesPersonTableAdapter
            CType(Me.radGridView1, System.ComponentModel.ISupportInitialize).BeginInit()
            CType(Me.radGridView1.MasterTemplate, System.ComponentModel.ISupportInitialize).BeginInit()
            CType(Me.salesPersonBindingSource, System.ComponentModel.ISupportInitialize).BeginInit()
            CType(Me.adventureWorksDataSet, System.ComponentModel.ISupportInitialize).BeginInit()
            Me.SuspendLayout()
            '
            'radGridView1
            '
            Me.radGridView1.BackColor = System.Drawing.SystemColors.Control
            Me.radGridView1.Cursor = System.Windows.Forms.Cursors.Default
            Me.radGridView1.Dock = System.Windows.Forms.DockStyle.Fill
            Me.radGridView1.Font = New System.Drawing.Font("Microsoft Sans Serif", 8.25!)
            Me.radGridView1.ForeColor = System.Drawing.SystemColors.ControlText
            Me.radGridView1.ImeMode = System.Windows.Forms.ImeMode.NoControl
            Me.radGridView1.Location = New System.Drawing.Point(0, 0)
            '
            'radGridView1
            '
            Me.radGridView1.MasterTemplate.Caption = "SalesPerson"
            GridViewDecimalColumn1.DataType = GetType(Integer)
            GridViewDecimalColumn1.FieldName = "SalesPersonID"
            GridViewDecimalColumn1.FormatString = ""
            GridViewDecimalColumn1.HeaderText = "ID"
            GridViewDecimalColumn1.IsAutoGenerated = True
            GridViewDecimalColumn1.Name = "SalesPersonID"
            GridViewDecimalColumn1.TextAlignment = System.Drawing.ContentAlignment.MiddleRight
            GridViewDecimalColumn1.Width = 120
            GridViewDecimalColumn2.DataType = GetType(Integer)
            GridViewDecimalColumn2.FieldName = "TerritoryID"
            GridViewDecimalColumn2.HeaderText = "TerritoryID"
            GridViewDecimalColumn2.IsAutoGenerated = True
            GridViewDecimalColumn2.IsVisible = False
            GridViewDecimalColumn2.Name = "TerritoryID"
            GridViewDecimalColumn2.TextAlignment = System.Drawing.ContentAlignment.MiddleRight
            GridViewDecimalColumn2.Width = 133
            GridViewDecimalColumn3.FieldName = "SalesQuota"
            GridViewDecimalColumn3.FormatString = ""
            GridViewDecimalColumn3.HeaderText = "Quota"
            GridViewDecimalColumn3.IsAutoGenerated = True
            GridViewDecimalColumn3.Name = "SalesQuota"
            GridViewDecimalColumn3.TextAlignment = System.Drawing.ContentAlignment.MiddleRight
            GridViewDecimalColumn3.Width = 120
            GridViewDecimalColumn4.FieldName = "Bonus"
            GridViewDecimalColumn4.FormatString = ""
            GridViewDecimalColumn4.HeaderText = "Bonus"
            GridViewDecimalColumn4.IsAutoGenerated = True
            GridViewDecimalColumn4.Name = "Bonus"
            GridViewDecimalColumn4.TextAlignment = System.Drawing.ContentAlignment.MiddleRight
            GridViewDecimalColumn4.Width = 120
            GridViewDecimalColumn5.FieldName = "CommissionPct"
            GridViewDecimalColumn5.FormatString = ""
            GridViewDecimalColumn5.HeaderText = "Commission Pct"
            GridViewDecimalColumn5.IsAutoGenerated = True
            GridViewDecimalColumn5.Name = "CommissionPct"
            GridViewDecimalColumn5.TextAlignment = System.Drawing.ContentAlignment.MiddleRight
            GridViewDecimalColumn5.Width = 120
            GridViewDecimalColumn6.FieldName = "SalesYTD"
            GridViewDecimalColumn6.FormatString = ""
            GridViewDecimalColumn6.HeaderText = "YTD"
            GridViewDecimalColumn6.IsAutoGenerated = True
            GridViewDecimalColumn6.Name = "SalesYTD"
            GridViewDecimalColumn6.TextAlignment = System.Drawing.ContentAlignment.MiddleRight
            GridViewDecimalColumn6.Width = 120
            GridViewDecimalColumn7.FieldName = "SalesLastYear"
            GridViewDecimalColumn7.FormatString = ""
            GridViewDecimalColumn7.HeaderText = "Sales Last Year"
            GridViewDecimalColumn7.IsAutoGenerated = True
            GridViewDecimalColumn7.Name = "SalesLastYear"
            GridViewDecimalColumn7.TextAlignment = System.Drawing.ContentAlignment.MiddleRight
            GridViewDecimalColumn7.Width = 120
            GridViewTextBoxColumn1.DataType = GetType(System.Guid)
            GridViewTextBoxColumn1.FieldName = "rowguid"
            GridViewTextBoxColumn1.HeaderText = "rowguid"
            GridViewTextBoxColumn1.IsAutoGenerated = True
            GridViewTextBoxColumn1.IsVisible = False
            GridViewTextBoxColumn1.Name = "rowguid"
            GridViewTextBoxColumn1.Width = 116
            GridViewDateTimeColumn1.FieldName = "ModifiedDate"
            GridViewDateTimeColumn1.HeaderText = "ModifiedDate"
            GridViewDateTimeColumn1.IsAutoGenerated = True
            GridViewDateTimeColumn1.IsVisible = False
            GridViewDateTimeColumn1.Name = "ModifiedDate"
            GridViewDateTimeColumn1.Width = 103
            GridViewDecimalColumn8.FormatString = ""
            GridViewDecimalColumn8.HeaderText = "Percent of Quota"
            GridViewDecimalColumn8.Name = "PercentQuota"
            GridViewDecimalColumn8.TextAlignment = System.Drawing.ContentAlignment.MiddleRight
            GridViewDecimalColumn8.Width = 37
            Me.radGridView1.MasterTemplate.Columns.AddRange(New Telerik.WinControls.UI.GridViewDataColumn() {GridViewDecimalColumn1, GridViewDecimalColumn2, GridViewDecimalColumn3, GridViewDecimalColumn4, GridViewDecimalColumn5, GridViewDecimalColumn6, GridViewDecimalColumn7, GridViewTextBoxColumn1, GridViewDateTimeColumn1, GridViewDecimalColumn8})
            Me.radGridView1.MasterTemplate.DataSource = Me.salesPersonBindingSource
            Me.radGridView1.Name = "radGridView1"
            Me.radGridView1.RightToLeft = System.Windows.Forms.RightToLeft.No
            Me.radGridView1.Size = New System.Drawing.Size(784, 357)
            Me.radGridView1.TabIndex = 0
            Me.radGridView1.Text = "radGridViewPreview"
            Me.radGridView1.ThemeName = "ControlDefault"
            '
            'salesPersonBindingSource
            '
            Me.salesPersonBindingSource.DataMember = "SalesPerson"
            Me.salesPersonBindingSource.DataSource = Me.adventureWorksDataSet
            '
            'adventureWorksDataSet
            '
            Me.adventureWorksDataSet.DataSetName = "AdventureWorksDataSet"
            Me.adventureWorksDataSet.SchemaSerializationMode = System.Data.SchemaSerializationMode.IncludeSchema
            '
            'salesPersonTableAdapter
            '
            Me.salesPersonTableAdapter.ClearBeforeFill = True
            '
            'RadGridViewLab2
            '
            Me.AutoScaleDimensions = New System.Drawing.SizeF(6.0!, 13.0!)
            Me.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font
            Me.ClientSize = New System.Drawing.Size(784, 357)
            Me.Controls.Add(Me.radGridView1)
            Me.Name = "RadGridViewLab2"
            Me.Text = "RadGridView Lab 2"
            CType(Me.radGridView1.MasterTemplate, System.ComponentModel.ISupportInitialize).EndInit()
            CType(Me.radGridView1, System.ComponentModel.ISupportInitialize).EndInit()
            CType(Me.salesPersonBindingSource, System.ComponentModel.ISupportInitialize).EndInit()
            CType(Me.adventureWorksDataSet, System.ComponentModel.ISupportInitialize).EndInit()
            Me.ResumeLayout(False)

        End Sub

		#End Region

		Private radGridView1 As Telerik.WinControls.UI.RadGridView
		Private adventureWorksDataSet As AdventureWorksDataSet
		Private salesPersonBindingSource As System.Windows.Forms.BindingSource
        Private salesPersonTableAdapter As AdventureWorksDataSetTableAdapters.SalesPersonTableAdapter
    End Class
End Namespace

